### ISSUE TITLE
Statistics are empty

### ISSUE THREAD

**Issue by epassaro** [gustavofariaa/FlashscoreScraping#11]
Hi!

I'm scraping this data:

```
npm run start country=argentina league=copa-de-la-liga-profesional-2023 headless
```

And all the `statistic` entries are empty lists. Is this a bug or something related to the data for this specific tournament?

Thanks
Your code is amazing!

**Comment by Waterbroodje** [comment]
Hey, I'm not the creator but I've made a fix:

https://gist.github.com/Waterbroodje/c69fe08b0847a003f9f58c30d576ff95

You need to go to `flashscorescraping/src/utils/index.js` and paste the code. I've tested it on Eredivisie 2023-2024, so not 100% that it will work on other leagues. Let me know if it helps.

**Comment by Waterbroodje** [comment]
Just tested, it works with every league.

**Comment by gustavofariaa** [comment]
Hello everyone,

@epassaro thank you for reporting this issue. I've just implemented an update to fix it.

@Waterbroodje your solution appears to resolve some aspects of the problem. However, it seems that the ID, along with the class, is dynamically generated, which may require periodic adjustments to the code.

With the new update to the code, I'm confident that the statistics are now being retrieved correctly. At least until Flashscore updates the page again! 😄
