### ISSUE TITLE
New/Missing Feature Request - Pulling the match round

### ISSUE THREAD

**Issue by brianmusundi** [gustavofariaa/FlashscoreScraping#12]
I'm hoping you can modify/Update the code to allow for pulling the match round as well on top of the current info dump. It makes it easier to clump the matches according to the weeks. 
Also for matches that are yet to play under the fixtures tab

**Comment by gustavofariaa** [comment]
These features weren’t on my radar, but I’ll explore adding them.
Keep in mind that the data collected might be used to derive additional information through post-processing, which could potentially provide the details you’re looking for.

The repository is open for contributions, so feel free to add any features if you’re interested!
