### ISSUE TITLE
No data is scrapped

### ISSUE THREAD

**Issue by Mazon7** [gustavofariaa/FlashscoreScraping#14]
Hello @gustavofariaa, could you please confirm whether the scrapper works properly now?

I followed the docs and run commands mentioned in the readme file. 
`npm run start country=brazil league=serie-a-2023 headless`
`npm run start country=england league=premier-league-2022-2023 path=./src/data type=csv`

However, I got only this log in the console and no data was scrapped:

Progress ████████████████████████████████████████ 100% | 0/0

Maybe something changed on the flashscore or we need to fix commands' parameters.

Thanks for your attention to my issue!

**Comment by gustavofariaa** [comment]
Sorry for the delay. I just tested the commands, and data is being collected normally with the same commands:
```bash
npm run start country=brazil league=serie-a-2023 headless
npm run start country=england league=premier-league-2022-2023 path=./src/data type=csv
```
It seems the scraper is working fine.
