### ISSUE TITLE
Token is required

### ISSUE THREAD

**Issue by Armando123x** [gustavofariaa/FlashscoreScraping#15]
I tried run the example command, but I had the next error:

`> flashscore-scraping@1.1.1 start /content/FlashscoreScraping
> node src/index.js "country=brazil" "league=serie-a-2023" "headless"

file:///content/FlashscoreScraping/node_modules/puppeteer/lib/esm/puppeteer/getConfiguration.js:98
    configuration.experiments ??= {};
                              ^^^

SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flashscore-scraping@1.1.1 start: `node src/index.js "country=brazil" "league=serie-a-2023" "headless"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flashscore-scraping@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-06-09T17_03_12_734Z-debug.log`

**Comment by gustavofariaa** [comment]
I ran the same command successfully.
What version are you currently using?
The issue might be due to an older Node.js version. Try updating Node.
