### ISSUE TITLE
Full list of parameters and leagues

### ISSUE THREAD

**Issue by miladavaz** [gustavofariaa/FlashscoreScraping#16]
Hi, 

Great thing you've created here, having a bit of fun with it.

Is there anywhere I can see a full list of parameters to pull? And, where do I find the league names as defined by your code?

**Comment by gustavofariaa** [comment]
Hi @miladavaz ,

The list of parameters is explained in the [README file](https://github.com/gustavofariaa/FlashscoreScraping?tab=readme-ov-file#data-example). 
Keep in mind that game statistics are dynamic and may vary depending on the league or match.

For league names, you can refer to the Flashscore URL. For example:

```bash
https://www.flashscore.com/football/spain/laliga-2023-2024
npm run start country=spain league=laliga-2023-2024
```
```bash
https://www.flashscore.com/football/germany/bundesliga-2023-2024
npm run start country=germany league=bundesliga-2023-2024
```
