### ISSUE TITLE
Problem With Statitics

### ISSUE THREAD

**Issue by DeSlay** [gustavofariaa/FlashscoreScraping#4]
![image](https://user-images.githubusercontent.com/44580853/111177840-e81bc280-85aa-11eb-9482-6904cbd31513.png)
![image](https://user-images.githubusercontent.com/44580853/111178084-19948e00-85ab-11eb-92bd-b420cee6773a.png)

Hello, I have a trouble with Statitics, the code doesn't work, can you help me ? 
I have a other question, the data.json output of main with just scraping, how can we use for to create a csv ? for example thanks you.

**Comment by Mateusza3** [comment]
Did you have problem with scraping code ?
